"""Compatibility exports for QQ input helpers."""

from kokoro.action.tools.qq.decision_utils import (
    _default_participation_system,
    _default_participation_user,
    _file_uri,
    _has_direct_social_signal,
    _most_attended_packet,
    _qq_decision_from_action_batch,
    _silence_reason_ignores_direct_signal,
    _sticker_cq,
    _sticker_query_for_packets,
    _sticker_segment,
)
from kokoro.action.tools.qq.memory_context import (
    _cognition_context_for_packets,
    _lookup_packet_memory,
    _memory_context_for_packets,
    _memory_counterpart_for_packet,
    _memory_query_for_packet,
    _recent_self_context_for_packets,
    _with_memory_context,
)
from kokoro.action.tools.qq.parsing import (
    _clip_log,
    _compact_character,
    _config_float,
    _config_int,
    _extract_json_object,
    _extract_json_string_field,
    _normalize_for_duplicate,
    _parse_json_object_slice,
    _safe_context,
    _salvage_partial_decision,
    build_raw_message_from_onebot,
    build_self_message,
    clean_qq_reply,
)
from kokoro.action.tools.qq.social_signals import (
    _clean_recall_anchor,
    _content_is_only_name_call,
    _detect_attention_lines,
    _detect_relation_lines,
    _extract_nonself_target,
    _format_packet_for_decision,
    _is_self_message,
    _latest_attention_message,
    _looks_like_misowned_task,
    _looks_like_search_request,
    _looks_like_social_feedback,
    _looks_like_technical_advice,
    _looks_like_unbacked_action_promise,
    _matched_self_alias,
    _packet_turn_key,
    _participant_names,
    _recall_anchors_for_messages,
    _recent_self_said_quiet,
    _recent_social_feedback,
    _reply_targets_self,
    _search_topic_from_recent_context,
    _self_aliases,
    _strip_cq_codes,
)
