"""Speech input tool module."""

from kokoro.action.tools.speech_input.audio_runtime import (
    PendingSpeechTurn,
    PendingSpeechTurnBuffer,
    MultiSpeechInputRuntime,
    SingleSpeechRuntime,
    SpeechInputStartup,
    create_default_conversation,
    create_multi_speech_runtime,
    create_multi_speech_runtime_from_outputs,
    create_partial_handler,
    create_single_speech_runtime,
    create_single_speech_runtime_from_outputs,
    create_single_partial_handler,
    flush_multi_speech_turn,
    flush_single_speech_turn,
    handle_barge_in,
    handle_direct_speech_turn,
    handle_single_direct_speech_turn,
    handle_stt_pool_turn,
    merge_text,
    prepare_default_input,
    queue_multi_user_utterance,
    queue_single_user_utterance,
    start_default_worker,
    turn_deadline_delay,
)
from kokoro.action.tools.speech_input.conversation import ConversationManager
from kokoro.action.tools.speech_input.overlap import OverlapClassifier, get_classifier
from kokoro.action.tools.speech_input.stt import create_default_recognizer, resolve_input_device
from kokoro.action.tools.speech_input.stt import SAMPLE_RATE

__all__ = [
    "ConversationManager",
    "OverlapClassifier",
    "PendingSpeechTurn",
    "SAMPLE_RATE",
    "PendingSpeechTurnBuffer",
    "MultiSpeechInputRuntime",
    "SingleSpeechRuntime",
    "SpeechInputStartup",
    "create_default_conversation",
    "create_default_recognizer",
    "create_partial_handler",
    "create_single_partial_handler",
    "create_single_speech_runtime",
    "create_single_speech_runtime_from_outputs",
    "create_multi_speech_runtime",
    "create_multi_speech_runtime_from_outputs",
    "flush_multi_speech_turn",
    "flush_single_speech_turn",
    "get_classifier",
    "handle_barge_in",
    "handle_direct_speech_turn",
    "handle_single_direct_speech_turn",
    "handle_stt_pool_turn",
    "merge_text",
    "prepare_default_input",
    "resolve_input_device",
    "queue_multi_user_utterance",
    "queue_single_user_utterance",
    "start_default_worker",
    "turn_deadline_delay",
]
