# 蓬莱专用的 LLM 配置。
# 此处设置会覆盖全局 config.toml 的同名配置。
# 没有在此列出的配置项自动使用全局默认值。

# 对话模型。使用智谱 CharGLM-4
llm_model = "charglm-4"

# LLM 服务地址
llm_url = "https://open.bigmodel.cn/api/paas/v4"

# API 密钥
api_key = "0860b32a2ee146c385bca37e8638a613.rLeJMEJCYYVYOFFD"
