"""Multi-character relay tool module."""

from kokoro.action.tools.multi_relay.relay import MultiRelayServer, RelayClient
from kokoro.action.tools.multi_relay.runtime import (
    MultiCliRuntimeBundle,
    MultiSessionRuntime,
    MultiToolTransports,
    MultiDialogueRuntime,
    MultiSpeechResources,
    MultiTurnPredictor,
    SpeechGate,
    create_cli_runtime,
    create_dialogue_runtime,
    create_speech_resources,
    create_state_machine,
    load_session_runtime,
    make_thread_safe_printer,
    print_output_startup_summary,
    print_startup_summary,
    play_auto_cycle,
    play_single_auto_turn,
    play_turn,
    run_auto_turns,
    save_chat_logs,
    shutdown_cli_runtime_bundle,
    shutdown_runtime,
    shutdown_runtime_outputs,
    start_cli_runtime,
    start_transports,
)

__all__ = [
    "MultiCliRuntimeBundle",
    "MultiRelayServer",
    "MultiDialogueRuntime",
    "MultiSessionRuntime",
    "MultiToolTransports",
    "MultiSpeechResources",
    "MultiTurnPredictor",
    "RelayClient",
    "SpeechGate",
    "create_cli_runtime",
    "create_dialogue_runtime",
    "create_speech_resources",
    "create_state_machine",
    "load_session_runtime",
    "make_thread_safe_printer",
    "print_output_startup_summary",
    "print_startup_summary",
    "play_auto_cycle",
    "play_single_auto_turn",
    "play_turn",
    "run_auto_turns",
    "save_chat_logs",
    "shutdown_cli_runtime_bundle",
    "shutdown_runtime",
    "shutdown_runtime_outputs",
    "start_cli_runtime",
    "start_transports",
]
